Added some games from Epic Games and GOG
ChimeraOS/chimera-data pull request #25
Opened 2022-03-17 13:11 UTC by Dei657

2022-03-17 22:52 UTC, alkazar requested changes
Thank you for taking the time to submit you testing results!

2022-03-17 22:52 UTC, alkazar commented on gamedb.yaml
> +- name: LEGO® Batman™: The Videogame
Titles with ':' need to be in quotes i.e.
"LEGO Batman: The Videogame"

2022-03-20 12:59 UTC, merged

2022-03-20 13:15 UTC, alkazar commented on gamedb.yaml
> +  banner: steam:313690
I just noticed there isn't a status for LEGO Batman 3. Is that intentional?

2022-03-20 13:32 UTC, Dei657 commented
During the videos, the game partially lags.  I have not decided what status to give.